### ISSUE TITLE
Error while using UploadBlobItem 

### ISSUE THREAD

**Issue by skandats** [srinivasadotnet/BluePrism_Reusable_VBOs#1]
Getting an error while using UploadBlobItem action. Error - The given path's format is not supported. Could you please help me
![UploadError](https://user-images.githubusercontent.com/87111862/144225033-c02716df-7367-4689-87b1-74ba4aa2f718.jpg)
?

**Comment by srinivasadotnet** [comment]
We have fixed the issue and pushed the latest object to GitHub. Please check the latest object.
